import {TileStore} from './tile-store.js';
import {decodeRoads,isRoad,nearestRoad,move,findRoute} from './navigation.js';
export async function mountWorld(host,{map,gameUrl,referenceUrl,tileManifest,tileBaseUrl,resolveTile,signal,onPosition=()=>{}}){
 const load=url=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('地図を読み込めませんでした'));im.src=url;});
 const [game,reference]=await Promise.all([load(gameUrl),load(referenceUrl)]);if(signal?.aborted)throw new DOMException('Aborted','AbortError');
 const tiles=new TileStore(tileManifest,{maxCache:12,resolve:resolveTile||(file=>new URL(file,tileBaseUrl).href)});
 const mask=decodeRoads(map);if(!isRoad(map,mask,map.spawn.x,map.spawn.y))throw Error('開始地点が通路外です');
 host.classList.add('world-view');host.innerHTML=`<canvas class="world-canvas" tabindex="0" aria-label="鶴瀬駅周辺の歩行地図"></canvas><header class="world-head"><div><small>TSURUSE / FIELD MAP</small><h1>鶴瀬駅周辺</h1></div><span>マスク固定版</span></header><nav class="world-toolbar"><button data-a="walk">歩き始める</button><button data-a="overview">全体</button><button data-a="source">元地図</button><button data-a="collision">通行範囲</button><button data-a="select">開始地点を選ぶ</button></nav><div class="world-notice" aria-live="polite">全体図です。「歩き始める」で移動できます。</div><div class="world-zoom"><button data-a="plus" aria-label="拡大">＋</button><button data-a="minus" aria-label="縮小">−</button></div><div class="world-stick" aria-label="移動パッド"><i></i></div><div class="world-footer"><span class="world-position"></span><span>矢印 / WASD · 道をタップして移動</span></div>`;
 const canvas=host.querySelector('canvas'),ctx=canvas.getContext('2d'),stick=host.querySelector('.world-stick'),knob=stick.querySelector('i'),notice=host.querySelector('.world-notice');const events=new AbortController(),opts={signal:events.signal};
 let width=1,height=1,dpr=1,zoom=1,cx=map.width/2,cy=map.height/2,mode='overview',source=false,collision=false,route=[],routeIndex=0,last=0,raf=0,alive=true,paused=false,select=false;const player={...map.spawn};let vx=0,vy=0,pointer=null,drag=null;const keys=new Set();
 const overlay=document.createElement('canvas');overlay.width=map.width;overlay.height=map.height;const oc=overlay.getContext('2d'),pixels=oc.createImageData(map.width,map.height);for(let i=0;i<mask.length;i++)if(mask[i]){pixels.data[i*4]=13;pixels.data[i*4+1]=222;pixels.data[i*4+2]=173;pixels.data[i*4+3]=190;}oc.putImageData(pixels,0,0);
 function message(s){notice.textContent=s;}function fit(){zoom=Math.min(width/map.width,(height-150)/map.height)*.95;cx=map.width/2;cy=map.height/2;}
 function resize(){width=host.clientWidth;height=host.clientHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);if(mode==='overview')fit();}
 const ro=new ResizeObserver(resize);ro.observe(host);resize();
 function cancel(){vx=vy=0;keys.clear();pointer=null;knob.style.transform='translate(0px,0px)';}
 function walk(){select=false;mode='walk';zoom=8;cx=player.x;cy=player.y;host.dataset.mode=mode;message('道をタップして移動。細い道は自動移動が便利です。');canvas.focus({preventScroll:true});}
 function zoomBy(scale){zoom=Math.max(.15,Math.min(8,zoom*scale));}
 for(const b of host.querySelectorAll('[data-a]'))b.addEventListener('click',()=>{const a=b.dataset.a;if(a==='walk')walk();if(a==='overview'){cancel();route=[];mode='overview';host.dataset.mode=mode;fit();message('ドラッグで見渡せます。');}if(a==='source'){source=!source;b.textContent=source?'ゲーム表示':'元地図';}if(a==='collision'){collision=!collision;b.setAttribute('aria-pressed',String(collision));}if(a==='plus')zoomBy(1.5);if(a==='minus')zoomBy(1/1.5);if(a==='select'){select=true;cancel();route=[];mode='overview';host.dataset.mode=mode;fit();message('試したい道路を選んでください。開始位置だけを変更します。');}},opts);
 function screenWorld(x,y){const r=canvas.getBoundingClientRect();return{x:cx+(x-r.left-width/2)/zoom,y:cy+(y-r.top-height/2)/zoom};}
 canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});drag={id:e.pointerId,x:e.clientX,y:e.clientY,cx,cy,moved:false};canvas.setPointerCapture(e.pointerId);},opts);
 canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId||mode==='walk')return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;cx=drag.cx-dx/zoom;cy=drag.cy-dy/zoom;},opts);
 canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag=null;if(moved)return;const point=screenWorld(e.clientX,e.clientY),target=nearestRoad(map,mask,point.x,point.y,Math.min(20,Math.max(2,12/zoom)));if(!target){message('この位置には読み取れた道路がありません。');return;}if(select){player.x=target.x;player.y=target.y;walk();return;}if(mode==='walk'){route=findRoute(map,mask,player,target)||[];routeIndex=0;message(route.length?'選んだ道路へ移動します。':'この道路への接続は元画像から確認できていません。');}else{cx=target.x;cy=target.y;zoom=4;}},opts);
 canvas.addEventListener('pointercancel',()=>drag=null,opts);
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoomBy(e.deltaY<0?1.15:1/1.15);},{...opts,passive:false});
 function updateStick(e){const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,n=Math.max(38,Math.hypot(dx,dy));vx=dx/n;vy=dy/n;if(Math.hypot(dx,dy)<7)vx=vy=0;knob.style.transform=`translate(${vx*38}px,${vy*38}px)`;route=[];}
 stick.addEventListener('pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;stick.setPointerCapture(pointer);updateStick(e);},opts);stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer)updateStick(e);},opts);for(const t of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(t,e=>{if(e.pointerId===pointer)cancel();},opts);
 host.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k)){e.preventDefault();keys.add(k);route=[];}},opts);host.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()),opts);window.addEventListener('blur',cancel,opts);host.addEventListener('focusout',e=>{if(!host.contains(e.relatedTarget))cancel();},opts);document.addEventListener('visibilitychange',()=>{cancel();last=0;},opts);
 function frame(t){if(!alive)return;const dt=last?Math.min(.04,(t-last)/1000):0;last=t;
 if(mode==='walk'&&!paused&&!document.hidden){let dx=vx+(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0),dy=vy+(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0);const n=Math.max(1,Math.hypot(dx,dy));move(map,mask,player,dx/n*map.speed*dt,dy/n*map.speed*dt);
 let distance=map.speed*dt;while(routeIndex<route.length&&distance>0){const p=route[routeIndex],len=Math.hypot(p.x-player.x,p.y-player.y);if(len<.001){routeIndex++;continue;}const amount=Math.min(distance,len),oldX=player.x,oldY=player.y;move(map,mask,player,(p.x-player.x)/len*amount,(p.y-player.y)/len*amount);distance-=amount;if(Math.hypot(player.x-oldX,player.y-oldY)<amount*.5){route=[];break;}if(Math.hypot(p.x-player.x,p.y-player.y)<.01)routeIndex++;}
 cx=player.x;cy=player.y;onPosition({...player});}
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#e9e5d8';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(width/2,height/2);ctx.scale(zoom,zoom);ctx.translate(-cx,-cy);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(source?reference:game,0,0,map.width,map.height);if(!source&&zoom>=6){const view={left:cx-width/2/zoom,top:cy-height/2/zoom,right:cx+width/2/zoom,bottom:cy+height/2/zoom};tiles.request(view);tiles.draw(ctx,view);}if(collision)ctx.drawImage(overlay,0,0);ctx.restore();
 const px=width/2+(player.x-cx)*zoom,py=height/2+(player.y-cy)*zoom;
 if(mode==='walk'){ctx.save();ctx.translate(Math.round(px),Math.round(py));ctx.fillStyle='#334a5566';ctx.beginPath();ctx.ellipse(0,0,7,3,0,0,7);ctx.fill();ctx.fillStyle='#315267';ctx.fillRect(-4,-4,3,5);ctx.fillRect(2,-4,3,5);ctx.fillStyle='#efd15b';ctx.fillRect(-6,-14,12,10);ctx.fillStyle='#f3c59d';ctx.fillRect(-4,-21,8,8);ctx.fillStyle='#dfce9b';ctx.fillRect(-7,-24,14,6);ctx.fillRect(-9,-19,18,3);ctx.strokeStyle='#866648';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(7,-8);ctx.lineTo(13,-25);ctx.stroke();ctx.strokeStyle='#f6ffff';ctx.beginPath();ctx.ellipse(15,-28,5,7,.25,0,7);ctx.stroke();ctx.restore();}else{ctx.fillStyle='#da714e';ctx.beginPath();ctx.arc(px,py,5,0,7);ctx.fill();}
 host.querySelector('.world-position').textContent=`${Math.round(zoom*100)}% · ${Math.floor(player.x)}, ${Math.floor(player.y)}${!source&&zoom>=6&&!tiles.getStatus().ready? (tiles.getStatus().failed?" · 区画を再読込中":" · 詳細読込中"):""}`;raf=requestAnimationFrame(frame);}
 host.dataset.mode=mode;raf=requestAnimationFrame(frame);
 return{getPosition:()=>({...player}),getTileStatus:()=>tiles.getStatus(),setPaused(value){paused=!!value;cancel();route=[];},destroy(){alive=false;tiles.destroy();cancelAnimationFrame(raf);ro.disconnect();events.abort();host.innerHTML='';host.classList.remove('world-view');}};
}
